package com.amanahconnect.report;

import com.amanahconnect.billing.Formats;
import com.amanahconnect.common.csv.CsvWriter;
import com.amanahconnect.report.ReportData.Align;
import com.amanahconnect.report.ReportData.Column;
import com.amanahconnect.report.ReportData.Row;
import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import org.openpdf.text.Document;
import org.openpdf.text.DocumentException;
import org.openpdf.text.Element;
import org.openpdf.text.Font;
import org.openpdf.text.FontFactory;
import org.openpdf.text.PageSize;
import org.openpdf.text.Paragraph;
import org.openpdf.text.Phrase;
import org.openpdf.text.Rectangle;
import org.openpdf.text.pdf.PdfPCell;
import org.openpdf.text.pdf.PdfPTable;
import org.openpdf.text.pdf.PdfWriter;
import org.springframework.stereotype.Component;

/** Turns a {@link ReportData} into CSV or PDF bytes. */
@Component
public class ReportWriters {

    private static final Color TEAL = new Color(0x07, 0x36, 0x3E);
    private static final Color GOLD = new Color(0x8A, 0x6A, 0x12);
    private static final Color MUTED = new Color(0x5B, 0x6F, 0x72);
    private static final Color STRIPE = new Color(0xF4, 0xF8, 0xF8);
    private static final DateTimeFormatter DATE = DateTimeFormatter.ofPattern("dd MMM yyyy", Locale.ENGLISH);

    /** UTF-8 with a byte-order mark (so Excel reads names correctly); amounts are plain decimals, text is guarded against formulas. */
    public byte[] csv(ReportData report) {
        CsvWriter csv = new CsvWriter();
        csv.row(report.columns().stream().map(Column::name).toArray());
        for (Row row : report.rows()) csv.row(csvCells(row));
        if (report.totals() != null) csv.row(csvCells(report.totals()));
        return ("﻿" + csv).getBytes(StandardCharsets.UTF_8);
    }

    private static Object[] csvCells(Row row) {
        return row.cells().stream().map(c -> c == null ? "" : c).toArray(); // BigDecimal, Long and LocalDate stay typed: CsvWriter leaves them unguarded
    }

    public byte[] pdf(ReportData report, String communityName) {
        boolean wide = report.columns().size() > 6;
        try {
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            Document document = new Document(wide ? PageSize.A4.rotate() : PageSize.A4, 36, 36, 40, 40);
            PdfWriter writer = PdfWriter.getInstance(document, out);
            writer.setPageEvent(new PageNumbers());
            document.addTitle(report.title());
            document.addCreator("Amanah Connect");
            document.open();
            document.add(new Paragraph(clean(communityName), font(11, Font.BOLD, GOLD)));
            document.add(new Paragraph(clean(report.title()), font(17, Font.BOLD, TEAL)));
            for (String line : report.context()) document.add(new Paragraph(clean(line), font(9, Font.NORMAL, MUTED)));
            document.add(new Paragraph(" "));

            PdfPTable table = new PdfPTable(report.columns().size());
            table.setWidthPercentage(100);
            table.setHeaderRows(1);
            for (Column column : report.columns()) {
                PdfPCell head = new PdfPCell(new Phrase(clean(column.name()), font(8.5f, Font.BOLD, Color.WHITE)));
                head.setBackgroundColor(TEAL);
                head.setPadding(5);
                head.setBorder(Rectangle.NO_BORDER);
                head.setHorizontalAlignment(column.align() == Align.RIGHT ? Element.ALIGN_RIGHT : Element.ALIGN_LEFT);
                table.addCell(head);
            }
            int index = 0;
            for (Row row : report.rows()) addRow(table, report, row, index++ % 2 == 1);
            if (report.totals() != null) addRow(table, report, report.totals(), false);
            document.add(table);
            if (report.rows().isEmpty()) {
                Paragraph none = new Paragraph("Nothing to report for this selection.", font(10, Font.ITALIC, MUTED));
                none.setSpacingBefore(10);
                document.add(none);
            }
            Paragraph footer = new Paragraph("Generated by Amanah Connect on " + DATE.format(LocalDate.now()) + ".", font(8, Font.NORMAL, MUTED));
            footer.setSpacingBefore(14);
            document.add(footer);
            document.close();
            return out.toByteArray();
        } catch (DocumentException e) {
            throw new IllegalStateException("Could not render the report PDF", e);
        }
    }

    private void addRow(PdfPTable table, ReportData report, Row row, boolean stripe) {
        for (int i = 0; i < report.columns().size(); i++) {
            Column column = report.columns().get(i);
            Object value = i < row.cells().size() ? row.cells().get(i) : null;
            PdfPCell cell = new PdfPCell(new Phrase(clean(text(value, column, report.currency())), font(8.5f, row.emphasised() ? Font.BOLD : Font.NORMAL, Color.BLACK)));
            cell.setPadding(4);
            cell.setBorder(Rectangle.BOTTOM);
            cell.setBorderColor(new Color(0xE3, 0xEA, 0xEB));
            cell.setHorizontalAlignment(column.align() == Align.RIGHT ? Element.ALIGN_RIGHT : Element.ALIGN_LEFT);
            if (row.emphasised()) cell.setBackgroundColor(new Color(0xEE, 0xF8, 0xF8));
            else if (stripe) cell.setBackgroundColor(STRIPE);
            table.addCell(cell);
        }
    }

    private static String text(Object value, Column column, String currency) {
        if (value == null) return "";
        if (value instanceof BigDecimal amount) return column.amount() ? Formats.amount(amount, currency) : amount.toPlainString();
        if (value instanceof LocalDate date) return DATE.format(date);
        return value.toString();
    }

    private static Font font(float size, int style, Color color) {
        return FontFactory.getFont(FontFactory.HELVETICA, size, style, color);
    }

    /** Helvetica covers Latin-1; anything else becomes "?". */
    private static String clean(String text) {
        if (text == null) return "";
        StringBuilder out = new StringBuilder();
        text.codePoints().forEach(cp -> out.append(cp >= 0x20 && cp <= 0xFF && cp != 0x7F ? new String(Character.toChars(cp)) : cp == '\n' ? " " : "?"));
        return out.toString();
    }

    private static final class PageNumbers extends org.openpdf.text.pdf.PdfPageEventHelper {
        @Override
        public void onEndPage(PdfWriter writer, Document document) {
            org.openpdf.text.pdf.ColumnText.showTextAligned(writer.getDirectContent(), Element.ALIGN_CENTER,
                    new Phrase("Page " + writer.getPageNumber(), font(8, Font.NORMAL, MUTED)), (document.right() + document.left()) / 2, document.bottom() - 18, 0);
        }
    }
}
